version: "3.9"
services:
  mongodb:
    container_name: mongo
    image: mongo:6-jammy
    volumes:
      - ./backend/data:/data
    ports:
      - "27017:27017"

  backend:
    container_name: backend
    build: ./backend
    env_file:
      - ./backend/.env.sample
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
  frontend:
    container_name: frontend
    build: ./frontend
    env_file:
      - ./frontend/.env.sample
    ports:
      - "5173:5173"
  redis:
    container_name: redis
    restart: unless-stopped
    image: redis:7.0.5-alpine
    ports:
      - "6380:6379"
volumes:
  data:
